### ISSUE TITLE
Unable to use with Scala 3.0.0

### ISSUE THREAD

**Issue by ckipp01** [alexarchambault/ammonite-runner#118]
When attempting to use with Scala 3

```
//script.sc
// scala 3.0.0
```

```
❯ cs launch io.github.alexarchambault.ammonite::ammonite-runner-cli:latest.release -- script.sc

Exception in thread "main" java.lang.Exception: Error getting Ammonite class path
        at ammrunner.cli.AmmRunner$.run(AmmRunner.scala:52)
        at ammrunner.cli.AmmRunner$.run(AmmRunner.scala:11)
        at caseapp.core.app.CaseApp.main(CaseApp.scala:82)
        at ammrunner.cli.AmmRunner.main(AmmRunner.scala)
Caused by: ammrunner.CoursierError: Error fetching Ammonite 2.4.0 for scala 3.0.0
        at ammrunner.AmmoniteFetcher.maybeResult$1(AmmoniteFetcher.scala:90)
        at ammrunner.AmmoniteFetcher.command(AmmoniteFetcher.scala:108)
        at ammrunner.cli.AmmRunner$.run(AmmRunner.scala:51)
        ... 3 more
Caused by: coursierapi.error.MultipleResolutionError: Error downloading com.lihaoyi:ammonite-repl-api_3.0.0:2.4.0
  not found: /Users/ckipp/.ivy2/local/com.lihaoyi/ammonite-repl-api_3.0.0/2.4.0/ivys/ivy.xml
  not found: https://repo1.maven.org/maven2/com/lihaoyi/ammonite-repl-api_3.0.0/2.4.0/ammonite-repl-api_3.0.0-2.4.0.pom
Error downloading org.scala-lang:scala-library:3.0.0
  not found: /Users/ckipp/.ivy2/local/org.scala-lang/scala-library/3.0.0/ivys/ivy.xml
  not found: https://repo1.maven.org/maven2/org/scala-lang/scala-library/3.0.0/scala-library-3.0.0.pom
Error downloading org.scala-lang:scala-reflect:3.0.0
  not found: /Users/ckipp/.ivy2/local/org.scala-lang/scala-reflect/3.0.0/ivys/ivy.xml
  not found: https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/3.0.0/scala-reflect-3.0.0.pom

        at coursierapi.error.MultipleResolutionError.of(MultipleResolutionError.java:28)
        at coursierapi.shaded.coursier.internal.api.ApiHelper$.doFetch(ApiHelper.scala:356)
        at coursierapi.shaded.coursier.internal.api.ApiHelper.doFetch(ApiHelper.scala)
        at coursierapi.Fetch.fetchResult(Fetch.java:244)
        at ammrunner.AmmoniteFetcher.maybeResult$1(AmmoniteFetcher.scala:87)
        ... 5 more
```
I'm sure this is due to the massive changes in https://github.com/com-lihaoyi/Ammonite/pull/1150. Just creating this so we can track in on the Metals side.

**Comment by ItoYo16u** [comment]
This is probably because ammonite uses  dependencies for 2.13.6 
 instead of  those for  3. 
What do you think of  retrying requests with  _2.13 suffix when request  for 3.x dependencies fails?

**Comment by eloots** [comment]
@ckipp01 
I presume this is now fixed?

Just tried (different invocation of the command though):

```
$ cat script.sc
//script.sc
// scala 3.0.0
println("Hello from a script")

$ cs launch com.lihaoyi:ammonite_3.0.0:2.4.0 -M ammonite.Main -- script.sc
Hello from a script
```

**Comment by ckipp01** [comment]
> @ckipp01
> I presume this is now fixed?
> 
> Just tried (different invocation of the command though):
> 
> ```
> $ cat script.sc
> //script.sc
> // scala 3.0.0
> println("Hello from a script")
> 
> $ cs launch com.lihaoyi:ammonite_3.0.0:2.4.0 -M ammonite.Main -- script.sc
> Hello from a script
> ```

Hey @eloots ! Nope, the issue is still present. In your example you're simply directly launching ammonite (which is available for Scala 3), but you're not actually using `ammonite-runner` (this project). `ammonite-runner` allows you to more dynamically fetch and launch the correct ammonite version defined in your project via comments. In your script up above, the `// scala 3.0.0` is just a comment, whereas with `ammonite-runner` it'd be using that value set the Scala version in your script.

**Comment by eloots** [comment]
Hi Chris; TIL! Interesting.
It turns out that running an ammonite Scala 3 REPL also still has issues. Compare the following two runs of respectively that `scala3-repl` and `amm`:

```scala
$ scala3-repl
scala> given Int = 5
lazy val given_Int: Int

scala> summon[Int]
val res0: Int = 5
```

Quite uneventful and straightforward

```scala
$ cs launch com.lihaoyi:ammonite_3.0.0:2.4.0 -M ammonite.Main
Loading...
Welcome to the Ammonite Repl 2.4.0 (Scala 3.0.0 Java 11.0.11)
@ given Int = 5
   |          .print(``, "``", _root_.scala.Some("<lazy>"))
   |                 ^
   |                 empty quoted identifier
Compilation Failed

@ given a:Int = 5
a: Int = <lazy>

@ summon[Int]
res1: Int = 5
```

In summary, in the case of ammonite, anonymous given instances produce and error whereas the scala3-repl works correctly.

**Comment by ckipp01** [comment]
> In summary, in the case of ammonite, anonymous given instances produce and error whereas the scala3-repl works correctly.

@eloots  I'd recommend reporting this over in the https://github.com/com-lihaoyi/Ammonite repo.

**Comment by i-void** [comment]
Same here: Error fetching Ammonite 2.5.2 for scala 3.0.2 in vscode with metals extension.
